name: Prettier
on: push
env:
  FILE_PATTERN: ./**/*.{ts,tsx}"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v2
      - name: node setup
        uses: actions/setup-node@v2
        with:
          node-version: 15.8.0
      - name: run prettier
        run: npx prettier --list-different ${FILE_PATTERN}
